# Form implementation generated from reading ui file 'newCalc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
from PyQt6 import QtCore, QtGui, QtWidgets

matrix = np.array([[1,0],[0, 1]], dtype=float)
rank = np.linalg.matrix_rank(matrix)
det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
eig = np.linalg.eigvals(matrix)
trace = np.linalg.trace(matrix)
trans = np.linalg.matrix_transpose(matrix)



class Ui_Calculator_window(object):
    
    def call_trace(self):
        try:
            matrix[0,0] = float(self.r1c1.toPlainText())
            #print("debug ", self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
            print(matrix)
            #return "%.3f" % np.round(np.linalg.trace(matrix), 3)
            return "{:.5f}".format(np.linalg.trace(matrix))
        except Exception as e:
            print("exception:", e)
            return "error"
        
    def call_rank(self):
        try:
            matrix[0,0] = float(self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
            return str(np.linalg.matrix_rank(matrix))
        except Exception as e:
            print("exception:", e)
            return "error"

    def call_inv(self):
        try :
            matrix[0,0] = float(self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
        except Exception as e:
            return "error"
        try:
            return str(np.linalg.inv(matrix))
        except np.linalg.LinAlgError as e:
            print("Singular:", e)
            return "singular"
    def call_det(self):
        try: 
            matrix[0,0] = float(self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
            return str(np.linalg.det(matrix))
        except Exception as e:
            print("exception:", e)
            return "error"
    def call_eig(self):
        try :
            matrix[0,0] = float(self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
        except Exception as e:
            return "error"
        try:
            return str(np.linalg.eigvals(matrix))
        except np.linalg.LinAlgError as e:
            print("Singular:", e)
            return "singular"
       
    def call_trans(self):
        try: 
            matrix[0,0] = float(self.r1c1.toPlainText())
            matrix[0,1] = float(self.r1c2.toPlainText())
            matrix[1,0] = float(self.r2c1.toPlainText())
            matrix[1,1] = float(self.r2c2.toPlainText())
            return str(np.linalg.matrix_transpose(matrix))
        except Exception as e:
            print("exception:", e)
            return "error"

    #def rank_clicked(self):
        # self.output_label.setStyleSheet("background-color: green;")

    def setupUi(self, Calculator_window):

        Calculator_window.setObjectName("Calculator_window")
        Calculator_window.resize(659, 545)
        self.centralwidget = QtWidgets.QWidget(parent=Calculator_window)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(30, 200, 221, 271))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(20)
        self.output_label.setFont(font)
        self.output_label.setAutoFillBackground(True)
        self.output_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.output_label.setText("")
        self.output_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_label.setWordWrap(True)
        self.output_label.setObjectName("output_label")
        self.rank_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(self.call_rank()))
        self.rank_button.setGeometry(QtCore.QRect(270, 290, 111, 91))
        #self.rank_button.clicked.connect(self.rank_clicked)
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.rank_button.setFont(font)
        self.rank_button.setObjectName("rank_button")
        self.trace_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(str(self.call_trace())))
        self.trace_button.setGeometry(QtCore.QRect(390, 290, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.trace_button.setFont(font)
        self.trace_button.setObjectName("trace_button")
        self.det_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(str(self.call_det())))
        self.det_button.setGeometry(QtCore.QRect(510, 290, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.det_button.setFont(font)
        self.det_button.setObjectName("det_button")
        self.trans_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(str(self.call_trans())))
        self.trans_button.setGeometry(QtCore.QRect(510, 380, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.trans_button.setFont(font)
        self.trans_button.setObjectName("trans_button")
        self.eig_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(str(self.call_eig())))
        self.eig_button.setGeometry(QtCore.QRect(270, 380, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.eig_button.setFont(font)
        self.eig_button.setObjectName("eig_button")
        self.inv_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it(str(self.call_inv())))
        self.inv_button.setGeometry(QtCore.QRect(390, 380, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.inv_button.setFont(font)
        self.inv_button.setObjectName("inv_button")
        self.new_matrix_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.clearBoxes())
        self.new_matrix_button.setGeometry(QtCore.QRect(270, 200, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.new_matrix_button.setFont(font)
        self.new_matrix_button.setObjectName("new_matrix_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.press_it("    "))
        self.clear_button.setGeometry(QtCore.QRect(510, 200, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(17)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
       
        self.r1c2 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.r1c2.setGeometry(QtCore.QRect(120, 50, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(30)
        self.r1c2.setFont(font)
        self.r1c2.setPlainText("")
        self.r1c2.setObjectName("r1c2")
        self.r2c2 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.r2c2.setGeometry(QtCore.QRect(120, 120, 71, 64))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(30)
        self.r2c2.setFont(font)
        self.r2c2.setPlainText("")
        self.r2c2.setObjectName("r2c2")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 391, 131))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.r2c1 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.r2c1.setGeometry(QtCore.QRect(40, 120, 71, 64))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(30)
        
        self.r2c1.setFont(font)
        self.r2c1.setPlainText("")
        self.r2c1.setObjectName("r2c1")
        self.r1c1 = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.r1c1.setGeometry(QtCore.QRect(40, 50, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Tiro Kannada")
        font.setPointSize(30)
        
        self.r1c1.setFont(font)
        self.r1c1.setPlainText("")
        self.r1c1.setObjectName("r1c1")
        
        Calculator_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Calculator_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 21))
        self.menubar.setObjectName("menubar")
        Calculator_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Calculator_window)
        self.statusbar.setObjectName("statusbar")
        Calculator_window.setStatusBar(self.statusbar)

        
        self.retranslateUi(Calculator_window)
        QtCore.QMetaObject.connectSlotsByName(Calculator_window)
       
    def press_it(self, pressed):
        self.output_label.setText(pressed)
    
    def clearBoxes(self):
        #clear text boxes
        self.r1c1.setPlainText(" ")
        self.r1c2.setPlainText(" ")
        self.r2c1.setPlainText(" ")
        self.r2c2.setPlainText(" ")
   
    def retranslateUi(self, Calculator_window):
        _translate = QtCore.QCoreApplication.translate
        Calculator_window.setWindowTitle(_translate("Calculator_window", "Calculator"))
        self.rank_button.setText(_translate("Calculator_window", "rank"))
        self.trace_button.setText(_translate("Calculator_window", "trace"))
        self.det_button.setText(_translate("Calculator_window", "determinant"))
        self.trans_button.setText(_translate("Calculator_window", "transpose"))
        self.eig_button.setText(_translate("Calculator_window", "eigenvalues"))
        self.inv_button.setText(_translate("Calculator_window", "inverse"))
        self.new_matrix_button.setText(_translate("Calculator_window", "new matrix"))
        self.clear_button.setText(_translate("Calculator_window", "clear"))
        self.label.setText(_translate("Calculator_window", "Linear Algebra Calculator"))
        self.label_2.setText(_translate("Calculator_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Welcome! Add your matrix in the boxes on the left. To reset the matrix, press &quot;new matrix&quot;. To clear the output screen, press &quot;clear&quot;. </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator_window = QtWidgets.QMainWindow()
    ui = Ui_Calculator_window()
    ui.setupUi(Calculator_window)
    Calculator_window.show()
    sys.exit(app.exec())
